name: loki
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
      - telemetry
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=loki
      - APP_ADDRESS=0.0.0.0:8080
      - CLIENT_URL=http://localhost:3000
      - SECRET_KEY=jwt-secret-key
      - CERT_PATH=/run/certs
      - SMART_ID_API_URL=https://sid.demo.sk.ee/smart-id-rp/v2
      - SMART_ID_DISPLAY_TEXT=Enter PIN1
      - MOBILE_ID_API_URL=https://tsp.demo.sk.ee/mid-api
      - MOBILE_ID_DISPLAY_TEXT=Enter PIN1
      - MOBILE_ID_TEXT_FORMAT=GSM-7
      - MOBILE_ID_LANGUAGE=ENG
      - RELYING_PARTY_UUID=00000000-0000-0000-0000-000000000000
      - RELYING_PARTY_NAME=DEMO
      - DATABASE_DSN=postgres://postgres:postgres@database:5432/loki-development?sslmode=disable
      - REDIS_URI=redis://redis:6379/0
      - TELEMETRY_URI=telemetry:4317
      - LOG_LEVEL=info
    networks:
      - loki-network

  database:
    image: postgres:16.4-alpine
    volumes:
      - loki-database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
    networks:
      - loki-network

  redis:
    image: redis:7.4-alpine
    volumes:
      - loki-redis:/var/lib/redis
    ports:
      - 6379:6379
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - loki-network

  telemetry:
    image: jaegertracing/all-in-one:1.64.0
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - loki-network

networks:
  loki-network:
    name: loki-network
    external: false

volumes:
  loki-database:
  loki-redis:
