name: loki
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=loki
      - APP_ADDRESS=0.0.0.0:8080
      - CLIENT_URL=http://localhost:3000
      - CERT_PATH=/run/certs
      - SMART_ID_API_URL=https://sid.demo.sk.ee/smart-id-rp/v2
      - SMART_ID_DISPLAY_TEXT=Enter PIN1
      - MOBILE_ID_API_URL=https://tsp.demo.sk.ee/mid-api
      - MOBILE_ID_DISPLAY_TEXT=Enter PIN1
      - MOBILE_ID_TEXT_FORMAT=GSM-7
      - MOBILE_ID_LANGUAGE=ENG
      - RELYING_PARTY_UUID=00000000-0000-0000-0000-000000000000
      - RELYING_PARTY_NAME=DEMO
      - DATABASE_DSN=postgres://postgres:postgres@database:5432/loki-development?sslmode=disable
      - REDIS_URI=redis://redis:6379/0
      - TELEMETRY_URI=telemetry:4317
      - LOG_LEVEL=info
    volumes:
      - ./certs:/run/certs
    networks:
      - loki-network

networks:
  loki-network:
    name: loki-network
    external: true

volumes:
  loki-database:
  loki-redis:
