site_name: Loki
site_url: https://tab.github.io/loki
site_author: tab
site_description: SSO service for authentication via Smart-ID and Mobile-ID

repo_name: tab/loki
repo_url: https://github.com/tab/loki

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md

docs_dir: docs
site_dir: site

theme:
  name: material
  language: en
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
