// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/repositories/scope.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/repositories/scope.go -destination=internal/app/repositories/scope_mock.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	models "loki/internal/app/models"
	db "loki/internal/app/repositories/db"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockScopeRepository is a mock of ScopeRepository interface.
type MockScopeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScopeRepositoryMockRecorder
	isgomock struct{}
}

// MockScopeRepositoryMockRecorder is the mock recorder for MockScopeRepository.
type MockScopeRepositoryMockRecorder struct {
	mock *MockScopeRepository
}

// NewMockScopeRepository creates a new mock instance.
func NewMockScopeRepository(ctrl *gomock.Controller) *MockScopeRepository {
	mock := &MockScopeRepository{ctrl: ctrl}
	mock.recorder = &MockScopeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScopeRepository) EXPECT() *MockScopeRepositoryMockRecorder {
	return m.recorder
}

// CreateUserScope mocks base method.
func (m *MockScopeRepository) CreateUserScope(ctx context.Context, params db.CreateUserScopeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserScope", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserScope indicates an expected call of CreateUserScope.
func (mr *MockScopeRepositoryMockRecorder) CreateUserScope(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserScope", reflect.TypeOf((*MockScopeRepository)(nil).CreateUserScope), ctx, params)
}

// FindByName mocks base method.
func (m *MockScopeRepository) FindByName(ctx context.Context, name string) (*models.Scope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*models.Scope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockScopeRepositoryMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockScopeRepository)(nil).FindByName), ctx, name)
}

// FindByUserId mocks base method.
func (m *MockScopeRepository) FindByUserId(ctx context.Context, id uuid.UUID) ([]models.Scope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", ctx, id)
	ret0, _ := ret[0].([]models.Scope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockScopeRepositoryMockRecorder) FindByUserId(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockScopeRepository)(nil).FindByUserId), ctx, id)
}
