// Code generated by MockGen. DO NOT EDIT.
// Source: internal/config/server/grpc.go
//
// Generated by this command:
//
//	mockgen -source=internal/config/server/grpc.go -destination=internal/config/server/grpc_mock.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGrpcServer is a mock of GrpcServer interface.
type MockGrpcServer struct {
	ctrl     *gomock.Controller
	recorder *MockGrpcServerMockRecorder
	isgomock struct{}
}

// MockGrpcServerMockRecorder is the mock recorder for MockGrpcServer.
type MockGrpcServerMockRecorder struct {
	mock *MockGrpcServer
}

// NewMockGrpcServer creates a new mock instance.
func NewMockGrpcServer(ctrl *gomock.Controller) *MockGrpcServer {
	mock := &MockGrpcServer{ctrl: ctrl}
	mock.recorder = &MockGrpcServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGrpcServer) EXPECT() *MockGrpcServerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockGrpcServer) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockGrpcServerMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockGrpcServer)(nil).Run))
}

// Shutdown mocks base method.
func (m *MockGrpcServer) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockGrpcServerMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockGrpcServer)(nil).Shutdown), ctx)
}
