// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/services/mobile_id.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/services/mobile_id.go -destination=internal/app/services/mobile_id_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	dto "loki/internal/app/models/dto"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMobileIdProvider is a mock of MobileIdProvider interface.
type MockMobileIdProvider struct {
	ctrl     *gomock.Controller
	recorder *MockMobileIdProviderMockRecorder
	isgomock struct{}
}

// MockMobileIdProviderMockRecorder is the mock recorder for MockMobileIdProvider.
type MockMobileIdProviderMockRecorder struct {
	mock *MockMobileIdProvider
}

// NewMockMobileIdProvider creates a new mock instance.
func NewMockMobileIdProvider(ctrl *gomock.Controller) *MockMobileIdProvider {
	mock := &MockMobileIdProvider{ctrl: ctrl}
	mock.recorder = &MockMobileIdProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMobileIdProvider) EXPECT() *MockMobileIdProviderMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockMobileIdProvider) CreateSession(ctx context.Context, params dto.CreateMobileIdSessionRequest) (*dto.MobileIdProviderSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, params)
	ret0, _ := ret[0].(*dto.MobileIdProviderSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockMobileIdProviderMockRecorder) CreateSession(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockMobileIdProvider)(nil).CreateSession), ctx, params)
}

// GetSessionStatus mocks base method.
func (m *MockMobileIdProvider) GetSessionStatus(id uuid.UUID) (*dto.MobileIdProviderSessionStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionStatus", id)
	ret0, _ := ret[0].(*dto.MobileIdProviderSessionStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionStatus indicates an expected call of GetSessionStatus.
func (mr *MockMobileIdProviderMockRecorder) GetSessionStatus(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionStatus", reflect.TypeOf((*MockMobileIdProvider)(nil).GetSessionStatus), id)
}
