// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/controllers/mobile_id.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/controllers/mobile_id.go -destination=internal/app/controllers/mobile_id_mock.go -package=controllers
//

// Package controllers is a generated GoMock package.
package controllers

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMobileIdController is a mock of MobileIdController interface.
type MockMobileIdController struct {
	ctrl     *gomock.Controller
	recorder *MockMobileIdControllerMockRecorder
	isgomock struct{}
}

// MockMobileIdControllerMockRecorder is the mock recorder for MockMobileIdController.
type MockMobileIdControllerMockRecorder struct {
	mock *MockMobileIdController
}

// NewMockMobileIdController creates a new mock instance.
func NewMockMobileIdController(ctrl *gomock.Controller) *MockMobileIdController {
	mock := &MockMobileIdController{ctrl: ctrl}
	mock.recorder = &MockMobileIdControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMobileIdController) EXPECT() *MockMobileIdControllerMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockMobileIdController) CreateSession(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateSession", w, r)
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockMobileIdControllerMockRecorder) CreateSession(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockMobileIdController)(nil).CreateSession), w, r)
}
