// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/controllers/sessions.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/controllers/sessions.go -destination=internal/app/controllers/sessions_mock.go -package=controllers
//

// Package controllers is a generated GoMock package.
package controllers

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionsController is a mock of SessionsController interface.
type MockSessionsController struct {
	ctrl     *gomock.Controller
	recorder *MockSessionsControllerMockRecorder
	isgomock struct{}
}

// MockSessionsControllerMockRecorder is the mock recorder for MockSessionsController.
type MockSessionsControllerMockRecorder struct {
	mock *MockSessionsController
}

// NewMockSessionsController creates a new mock instance.
func NewMockSessionsController(ctrl *gomock.Controller) *MockSessionsController {
	mock := &MockSessionsController{ctrl: ctrl}
	mock.recorder = &MockSessionsControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionsController) EXPECT() *MockSessionsControllerMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockSessionsController) Authenticate(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Authenticate", w, r)
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockSessionsControllerMockRecorder) Authenticate(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockSessionsController)(nil).Authenticate), w, r)
}

// GetStatus mocks base method.
func (m *MockSessionsController) GetStatus(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetStatus", w, r)
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockSessionsControllerMockRecorder) GetStatus(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockSessionsController)(nil).GetStatus), w, r)
}
