// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/controllers/users.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/controllers/users.go -destination=internal/app/controllers/users_mock.go -package=controllers
//

// Package controllers is a generated GoMock package.
package controllers

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsersController is a mock of UsersController interface.
type MockUsersController struct {
	ctrl     *gomock.Controller
	recorder *MockUsersControllerMockRecorder
	isgomock struct{}
}

// MockUsersControllerMockRecorder is the mock recorder for MockUsersController.
type MockUsersControllerMockRecorder struct {
	mock *MockUsersController
}

// NewMockUsersController creates a new mock instance.
func NewMockUsersController(ctrl *gomock.Controller) *MockUsersController {
	mock := &MockUsersController{ctrl: ctrl}
	mock.recorder = &MockUsersControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersController) EXPECT() *MockUsersControllerMockRecorder {
	return m.recorder
}

// Me mocks base method.
func (m *MockUsersController) Me(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Me", w, r)
}

// Me indicates an expected call of Me.
func (mr *MockUsersControllerMockRecorder) Me(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Me", reflect.TypeOf((*MockUsersController)(nil).Me), w, r)
}
